"""
Simple test script to visualize sampled point clouds.

This script loads and visualizes point clouds generated by surface_to_samples.py
"""

import numpy as np
import polyscope as ps
import argparse
from pathlib import Path


def visualize_point_cloud(npy_path, labels_path=None, point_radius=0.003):
    """
    Visualize a point cloud from NPY file.
    
    Args:
        npy_path: Path to .npy file containing points
        labels_path: Optional path to .labels.npy file
        point_radius: Radius for point visualization
    """
    # Load points
    points = np.load(npy_path)
    print(f"Loaded {len(points)} points from {npy_path}")
    print(f"Point cloud bounds:")
    print(f"  X: [{points[:, 0].min():.3f}, {points[:, 0].max():.3f}]")
    print(f"  Y: [{points[:, 1].min():.3f}, {points[:, 1].max():.3f}]")
    print(f"  Z: [{points[:, 2].min():.3f}, {points[:, 2].max():.3f}]")
    
    # Initialize polyscope
    ps.init()
    ps.set_ground_plane_mode("shadow_only")
    
    # Register point cloud
    cloud = ps.register_point_cloud("sampled_points", points, radius=point_radius)
    
    # Load and add labels if available
    if labels_path and Path(labels_path).exists():
        labels = np.load(labels_path)
        print(f"Loaded labels: {len(np.unique(labels))} unique surfaces")
        
        # Add scalar quantity for surface labels
        cloud.add_scalar_quantity("surface_id", labels, enabled=True, cmap='rainbow')
        
        # Print surface distribution
        unique, counts = np.unique(labels, return_counts=True)
        print("\nPoint distribution per surface:")
        for surf_id, count in zip(unique, counts):
            print(f"  Surface {surf_id}: {count} points ({100*count/len(points):.1f}%)")
    else:
        print("No labels file found")
    
    print("\nShowing visualization...")
    ps.show()


def compare_multiple_samples(npy_dir, pattern="*.npy", max_files=5):
    """
    Load and compare multiple point cloud files.
    
    Args:
        npy_dir: Directory containing NPY files
        pattern: File pattern to match
        max_files: Maximum number of files to load
    """
    npy_dir = Path(npy_dir)
    npy_files = sorted(npy_dir.rglob(pattern))
    
    if not npy_files:
        print(f"No NPY files found in {npy_dir}")
        return
    
    print(f"Found {len(npy_files)} NPY files")
    print(f"Loading first {min(max_files, len(npy_files))} files...")
    
    # Initialize polyscope
    ps.init()
    ps.set_ground_plane_mode("shadow_only")
    
    # Load each file
    for i, npy_path in enumerate(npy_files[:max_files]):
        points = np.load(npy_path)
        
        # Offset each point cloud for comparison
        offset = np.array([i * 2.0, 0, 0])
        points_offset = points + offset
        
        # Register point cloud
        cloud_name = f"model_{i}_{npy_path.stem}"
        cloud = ps.register_point_cloud(cloud_name, points_offset, radius=0.003)
        
        print(f"{i+1}. {npy_path.name}: {len(points)} points")
        
        # Try to load labels
        label_path = npy_path.with_suffix('.labels.npy')
        if label_path.exists():
            labels = np.load(label_path)
            cloud.add_scalar_quantity("surface_id", labels, enabled=True, cmap='rainbow')
    
    print("\nShowing comparison visualization...")
    print("Point clouds are offset along X-axis for comparison")
    ps.show()


def main():
    parser = argparse.ArgumentParser(description='Visualize sampled point clouds')
    parser.add_argument('input', type=str, 
                       help='Path to NPY file or directory')
    parser.add_argument('--labels', type=str, default=None,
                       help='Path to labels NPY file (if not auto-detected)')
    parser.add_argument('--compare', action='store_true',
                       help='Compare multiple files in directory')
    parser.add_argument('--max_files', type=int, default=5,
                       help='Maximum files to load in compare mode')
    parser.add_argument('--radius', type=float, default=0.003,
                       help='Point radius for visualization')
    
    args = parser.parse_args()
    
    input_path = Path(args.input)
    
    if args.compare or input_path.is_dir():
        # Compare mode
        compare_multiple_samples(input_path, max_files=args.max_files)
    else:
        # Single file mode
        if not input_path.exists():
            print(f"Error: {input_path} not found")
            return
        
        # Auto-detect labels file
        labels_path = args.labels
        if labels_path is None:
            labels_path = input_path.with_suffix('.labels.npy')
        
        visualize_point_cloud(input_path, labels_path, point_radius=args.radius)


if __name__ == '__main__':
    main()


