"""
Interactive test script to visualize sampled point clouds.

This script loads and visualizes point clouds generated by surface_to_samples.py
with an interactive slider/input interface for browsing multiple files.
"""

import numpy as np
import polyscope as ps
import polyscope.imgui as psim
import argparse
from pathlib import Path

# Global variables for interactive mode
current_idx = 0
max_idx = 0
npy_files = []
point_radius = 0.003
show_labels = True
current_cloud = None


def load_and_display(idx):
    """Load and display point cloud at given index"""
    global current_cloud, npy_files, point_radius, show_labels
    
    # Clear existing visualization
    ps.remove_all_structures()
    
    # Get file path
    npy_path = npy_files[idx]
    
    # Load points
    points = np.load(npy_path)
    
    # Register point cloud
    current_cloud = ps.register_point_cloud("point_cloud", points, radius=point_radius)
    
    # Try to load labels
    label_path = npy_path.with_suffix('.labels.npy')
    if label_path.exists() and show_labels:
        labels = np.load(label_path)
        current_cloud.add_scalar_quantity("surface_id", labels, enabled=True, cmap='rainbow')
        
        # Print info
        print(f"\n[{idx}] {npy_path.name}")
        print(f"  Points: {len(points)}")
        print(f"  Surfaces: {len(np.unique(labels))}")
        
        # Print bounds
        print(f"  Bounds: X[{points[:, 0].min():.2f}, {points[:, 0].max():.2f}] "
              f"Y[{points[:, 1].min():.2f}, {points[:, 1].max():.2f}] "
              f"Z[{points[:, 2].min():.2f}, {points[:, 2].max():.2f}]")
        
        # Print distribution
        unique, counts = np.unique(labels, return_counts=True)
        if len(unique) <= 10:
            print(f"  Distribution: ", end="")
            for surf_id, count in zip(unique, counts):
                print(f"S{surf_id}:{count} ", end="")
            print()
    else:
        print(f"\n[{idx}] {npy_path.name}")
        print(f"  Points: {len(points)}")
        print(f"  Bounds: X[{points[:, 0].min():.2f}, {points[:, 0].max():.2f}] "
              f"Y[{points[:, 1].min():.2f}, {points[:, 1].max():.2f}] "
              f"Z[{points[:, 2].min():.2f}, {points[:, 2].max():.2f}]")


def callback():
    """Polyscope callback for interactive controls"""
    global current_idx, max_idx, npy_files, point_radius, show_labels
    
    psim.Text("Point Cloud Viewer")
    psim.Separator()
    
    # Index controls
    slider_changed, slider_idx = psim.SliderInt("Sample Index", current_idx, 0, max_idx)
    if slider_changed and slider_idx != current_idx:
        current_idx = slider_idx
        load_and_display(current_idx)
    
    input_changed, input_idx = psim.InputInt("Go To Index", current_idx)
    if input_changed:
        input_idx = max(0, min(max_idx, input_idx))
        if input_idx != current_idx:
            current_idx = input_idx
            load_and_display(current_idx)
    
    psim.Separator()
    psim.Text(f"Current: {current_idx} / {max_idx}")
    psim.Text(f"File: {npy_files[current_idx].name}")
    
    # Display options
    psim.Separator()
    psim.Text("Display Options:")
    
    changed, new_radius = psim.SliderFloat("Point Radius", point_radius, 0.001, 0.01)
    if changed:
        point_radius = new_radius
        if current_cloud is not None:
            current_cloud.set_radius(point_radius)
    
    changed, show_labels = psim.Checkbox("Show Surface Labels", show_labels)
    if changed:
        load_and_display(current_idx)
    
    # Navigation buttons
    psim.Separator()
    if psim.Button("Previous (←)") or psim.IsKeyPressed(psim.ImGuiKey_LeftArrow):
        if current_idx > 0:
            current_idx -= 1
            load_and_display(current_idx)
    
    psim.SameLine()
    if psim.Button("Next (→)") or psim.IsKeyPressed(psim.ImGuiKey_RightArrow):
        if current_idx < max_idx:
            current_idx += 1
            load_and_display(current_idx)
    
    # Info
    psim.Separator()
    psim.Text("=== Controls ===")
    psim.Text("Use ← → arrow keys to navigate")
    psim.Text("Adjust point radius for better view")


def interactive_viewer(npy_dir, initial_idx=0, radius=0.003):
    """
    Interactive viewer for point clouds in a directory.
    
    Args:
        npy_dir: Directory containing NPY files
        initial_idx: Initial file index to display
        radius: Initial point radius
    """
    global current_idx, max_idx, npy_files, point_radius
    
    npy_dir = Path(npy_dir)
    
    # Find all NPY files (excluding label files)
    all_files = sorted(npy_dir.rglob("*.npy"))
    npy_files = [f for f in all_files if not f.name.endswith('.labels.npy')]
    
    if not npy_files:
        print(f"No NPY files found in {npy_dir}")
        return
    
    print(f"Found {len(npy_files)} point cloud files")
    
    # Initialize globals
    max_idx = len(npy_files) - 1
    current_idx = min(initial_idx, max_idx)
    point_radius = radius
    
    # Initialize polyscope
    ps.init()
    ps.set_ground_plane_mode("shadow_only")
    ps.set_user_callback(callback)
    
    # Load initial point cloud
    load_and_display(current_idx)
    
    # Show interface
    print("\n" + "="*80)
    print("Interactive Point Cloud Viewer")
    print("  - Use slider or input to select file index")
    print("  - Use arrow keys (← →) to navigate")
    print("  - Adjust point radius for better visualization")
    print("  - Toggle surface labels if available")
    print("="*80 + "\n")
    
    ps.show()


def visualize_single_file(npy_path, labels_path=None, radius=0.003):
    """
    Visualize a single point cloud file (non-interactive).
    
    Args:
        npy_path: Path to .npy file containing points
        labels_path: Optional path to .labels.npy file
        radius: Point radius for visualization
    """
    # Load points
    points = np.load(npy_path)
    print(f"Loaded {len(points)} points from {npy_path}")
    print(f"Point cloud bounds:")
    print(f"  X: [{points[:, 0].min():.3f}, {points[:, 0].max():.3f}]")
    print(f"  Y: [{points[:, 1].min():.3f}, {points[:, 1].max():.3f}]")
    print(f"  Z: [{points[:, 2].min():.3f}, {points[:, 2].max():.3f}]")
    
    # Initialize polyscope
    ps.init()
    ps.set_ground_plane_mode("shadow_only")
    
    # Register point cloud
    cloud = ps.register_point_cloud("sampled_points", points, radius=radius)
    
    # Load and add labels if available
    if labels_path and Path(labels_path).exists():
        labels = np.load(labels_path)
        print(f"Loaded labels: {len(np.unique(labels))} unique surfaces")
        
        # Add scalar quantity for surface labels
        cloud.add_scalar_quantity("surface_id", labels, enabled=True, cmap='rainbow')
        
        # Print surface distribution
        unique, counts = np.unique(labels, return_counts=True)
        print("\nPoint distribution per surface:")
        for surf_id, count in zip(unique, counts):
            print(f"  Surface {surf_id}: {count} points ({100*count/len(points):.1f}%)")
    else:
        print("No labels file found")
    
    print("\nShowing visualization...")
    ps.show()


def main():
    parser = argparse.ArgumentParser(
        description='Interactive visualizer for sampled point clouds'
    )
    parser.add_argument('input', type=str, 
                       help='Path to NPY file or directory')
    parser.add_argument('--index', type=int, default=0,
                       help='Initial file index in directory mode (default: 0)')
    parser.add_argument('--labels', type=str, default=None,
                       help='Path to labels NPY file (for single file mode)')
    parser.add_argument('--radius', type=float, default=0.003,
                       help='Point radius for visualization (default: 0.003)')
    parser.add_argument('--non-interactive', action='store_true',
                       help='Disable interactive mode (for single file)')
    
    args = parser.parse_args()
    
    input_path = Path(args.input)
    
    if not input_path.exists():
        print(f"Error: {input_path} not found")
        return
    
    if input_path.is_dir():
        # Directory mode: interactive viewer
        interactive_viewer(input_path, initial_idx=args.index, radius=args.radius)
    else:
        # Single file mode
        if args.non_interactive:
            # Non-interactive visualization
            labels_path = args.labels
            if labels_path is None:
                labels_path = input_path.with_suffix('.labels.npy')
            visualize_single_file(input_path, labels_path, radius=args.radius)
        else:
            # Interactive mode for single file (treat parent dir as directory)
            parent_dir = input_path.parent
            all_files = sorted(parent_dir.glob("*.npy"))
            npy_files_in_dir = [f for f in all_files if not f.name.endswith('.labels.npy')]
            
            if input_path in npy_files_in_dir:
                initial_idx = npy_files_in_dir.index(input_path)
                interactive_viewer(parent_dir, initial_idx=initial_idx, radius=args.radius)
            else:
                print(f"Warning: {input_path} not found in directory listing")
                labels_path = args.labels
                if labels_path is None:
                    labels_path = input_path.with_suffix('.labels.npy')
                visualize_single_file(input_path, labels_path, radius=args.radius)


if __name__ == '__main__':
    main()


