trainer:
    model_name: "GPT_INIT_142M"
    train_config: "train_0105_small_vae_excl_2"
    train_name: "train_l20_ablation_no_mask"
    wandb_project: "Experiment-Placeholder_mask"
    wandb_run_name: "no_mask"
    enable_placeholder_mask: false
    out_dir: "/deemos-research-area-d/meshgen/cad/checkpoints/GPT_INIT_142M/train_l20_ablation_no_mask/"

    use_sample_dataset: false
    freeze_conditioner: false
    conditioner_lr_scale: 1.0
    fsdp_state_dict_type: "full"

    # 单卡 L20 配置：
    #   global_batch_size = micro_batch_size × 2 = 32
    #   micro_batch_size  = 16
    #   gradient_accumulation_steps = 32 / (1 GPU × 16) = 2
    max_tokens: 1e8
    global_batch_size: 32
    micro_batch_size: 16
    learning_rate: 1e-4
    total_evals: 400
    warmup_tokens: null
    log_step_interval: 10
    save_step_interval: 500
    eval_step_interval: 100000000000000
    num_extrapol: 4

    weight_decay: 1e-1
    beta1: 0.9
    beta2: 0.95
    grad_clip: 1.0
    decay_lr: true
    min_lr: 1e-5

    num_epochs: 500
    use_michelangelo_grad: false
    find_unused_parameters: true


model:
  name: lit_gpt.model.GPT
  params:
    config:
      org: Lightning-AI
      name: Diff_LLaMA_142M
      block_size: 1000
      vocab_size: 1028
      padding_multiple: 64
      padded_vocab_size: 1028
      n_layer: 15
      n_head: 12
      n_embd: 768
      rotary_percentage: 1.0
      parallel_residual: false
      bias: false
      n_query_groups: 12
      shared_attention_norm: false
      _norm_class: FusedRMSNorm
      norm_eps: 1.0e-5
      _mlp_class: LLaMAMLP
      intermediate_size: 3072
      condense_ratio: 1
    use_michelangelo: true
    michelangelo_config_path: /deemos-research-area-d/meshgen/cad/CLR-Wire/third_party/Michelangelo/configs/aligned_shape_latents/shapevae-256.yaml
    michelangelo_ckpt_path: /deemos-research-area-d/meshgen/cad/CLR-Wire/third_party/Michelangelo/checkpoints/aligned_shape_latents/shapevae-256.ckpt
    build_conditioner: false
    freeze_conditioner: false

vae:
  name: src.vae.vae_v4_dcae_fsq.DCAE_FSQ_VAE
  pred_is_closed: true
  load_ckpt: true
  params:
      input_size: 4
      in_channels: 3
      latent_channels: 3
      width_base: 64
      fsq_levels: [8, 5, 5, 5]
      num_codebooks: 6
  checkpoint_folder: /deemos-research-area-d/meshgen/cad/CLR-Wire/checkpoints/train_1223_vae_v4_bspline_only_dcae_fsq_6tokens_1024
  checkpoint_file_name: model-10.pt

data_train:
  name: src.dataset.dataset_v4_tokenize_all.dataset_compound_tokenize_all_cache
  params:
    cache_file: /deemos-research-area-d/meshgen/cad/data/abc_step_pc_correct_normal/cache_fix_order_new/cache_1-9_fix_order.pkl
    replace_file_header: ''
    rts_codebook_dir: /deemos-research-area-d/meshgen/cad/CLR-Wire/assets/codebook_scale_1.2
    max_tokens: 1000
    canonical: true
    detect_closed: false
    bspline_fit_threshold: 1e-2
    codebook_size: 1024
    replica: 1
    rotation_augment: true
    point_augment: true
    point_augment_intensity: 0.002
    pc_shape: 4096
    emphasize_long: false
    min_surface_threshold: 0.01

data_val:
  name: src.dataset.dataset_v4_tokenize_all_inference.dataset_compound_tokenize_all_cache_inference
  params:
    cache_file: /deemos-research-area-d/meshgen/cad/data/abc_step_pc_correct_normal/cache_test_new/cache_00.pkl
    replace_file_header: ''
    rts_codebook_dir: /deemos-research-area-d/meshgen/cad/CLR-Wire/assets/codebook_scale_1.2
    max_tokens: 1000
    canonical: true
    detect_closed: false
    bspline_fit_threshold: 1e-2
    codebook_size: 1024
    replica: 1
    rotation_augment: false
    point_augment: false
    point_augment_intensity: 0.002
    pc_shape: 4096
    pc_shape_highres: 10240
    min_surface_threshold: 0.01
    inference: true
