resume_training: false
from_start: false

epochs: 1000
batch_size: 256
lr: 0.00001
num_workers: 6
num_gpus: 6

grad_accum_every: 1
ema_update_every: 10
max_grad_norm: 1.0

val_every_epoch: 1
save_every_epoch: 50
log_every_step: 10

use_wandb_tracking: true
wandb_project_name: CLR-classification
wandb_run_name: surface_cls_nope

DATA:
    replication: 1
    train_points_path: /home/qindafei/CAD/abc_json_with_curve/surface_class/points_train.npy
    train_labels_path: /home/qindafei/CAD/abc_json_with_curve/surface_class/class_label_train.npy
    val_points_path: /home/qindafei/CAD/abc_json_with_curve/surface_class/points_val.npy
    val_labels_path: /home/qindafei/CAD/abc_json_with_curve/surface_class/class_label_val.npy

MODEL:
    in_dim: 3
    out_dim: 6 # Num classes
    depth: 12
    dim: 256
    heads: 8
    res: 16
    use_pe: false
    checkpoint_folder: checkpoints/classification_nope
    checkpoint_file_name: model-62.pt 