resume_training: false
from_start: true

epochs: 1000
batch_size: 256
lr: 0.00001
rts_loss_weight: 0
cone_loss_weight: 0
num_classes: 6
num_workers: 5
num_gpus: 5

grad_accum_every: 1
ema_update_every: 10
max_grad_norm: 1.0

val_every_epoch: 1
save_every_epoch: 50
log_every_step: 10

use_wandb_tracking: true
wandb_project_name: CLR-cls-rts
wandb_run_name: train_old_dataset_only_cls

DATA:
    replication: 1
    train_data_path: /home/qindafei/CAD/abc_json_with_curve/surface_class/for_cls_rts_train.pkl
    val_data_path: /home/qindafei/CAD/abc_rts_0612_filtered_val.pkl

MODEL:
    in_dim: 3
    out_dim: 16 # 6 cls + 9 rts + 1 cone
    depth: 12
    dim: 256
    heads: 8
    res: 16
    checkpoint_folder: checkpoints/cls-rts-only-cls-old-dataset
    checkpoint_file_name: model-62.pt 