resume_training: false
from_start: false

epochs: 400
batch_size: 256 # 1024
lr: 0.0003
num_workers: 48
num_gpus: 6

grad_accum_every: 2
ema_update_every: 20
max_grad_norm: 5.

val_every_epoch: 1
save_every_epoch: 10
log_every_step: 10

# Visual evaluation settings
visual_eval_every_step: 1  # Visualize every 5000 steps
num_visual_samples: 4  # Number of samples to visualize

use_wandb_tracking: true
wandb_project_name: CLR-surface
wandb_run_name: normalized_try_1k_samples


DATA:
    train_set_file_path: /home/qindafei/CAD/abc_surfaces/balanced_train/normalized_surface_points_train.npy
    val_set_file_path: /home/qindafei/CAD/abc_surfaces/normalized_surface_points_val.npy
    replication: 1
    recon_dir_path: /home/qindafei/CAD/abc_surfaces/normalized_surface_points_val.npy

MODEL:
    in_channels: 3
    out_channels: 3
    latent_channels: 3

    down_block_types: [
      'DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D'
    ]
    up_block_types: [
      'UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D'
    ]
    
    block_out_channels: [
      64, 128, 256, 512
    ]

    layers_per_block: 2
    act_fn: 'silu'
    norm_num_groups: 8
    sample_points_num: 16

    kl_weight: 0.000005

    checkpoint_folder: checkpoints/checkpoints_normalized_surface_vae_debug
    checkpoint_file_name: model-04.pt
