resume_training: false
from_start: true

epochs: 1200
batch_size: 256  # Adjusted for B-spline model
lr: 0.00001
num_workers: 48
num_gpus: 6

grad_accum_every: 4
ema_update_every: 20
max_grad_norm: 5.

val_every_epoch: 1
save_every_epoch: 10
log_every_step: 10

# Visual evaluation settings
visual_eval_every_step: 100  # Visualize every 100 steps for B-spline debugging
num_visual_samples: 8  # Number of samples to visualize

use_wandb_tracking: true
wandb_project_name: CLR-surface-bspline
wandb_run_name: normalized_train_from_scratch_70epoch_64latent

DATA:
    # bs_path: /home/qindafei/CAD/abc_surfaces_cp/normalized_approx_train.npy
    # points_path: /home/qindafei/CAD/abc_surfaces_cp/normalized_sampled_surface_train.npy
    bs_path: /home/qindafei/CAD/abc_surfaces_cp/balanced_data/normalized_approx_train.npy
    points_path: /home/qindafei/CAD/abc_surfaces_cp/balanced_data/normalized_sampled_surface_train.npy

    val_bs_path: /home/qindafei/CAD/abc_surfaces_cp/normalized_approx_val.npy
    val_points_path: /home/qindafei/CAD/abc_surfaces_cp/normalized_sampled_surface_val.npy

    test_bs_path: /home/qindafei/CAD/abc_surfaces_cp/normalized_approx_test.npy
    test_points_path: /home/qindafei/CAD/abc_surfaces_cp/normalized_sampled_surface_test.npy
    replication: 1

MODEL:
    in_channels: 3
    out_channels: 3
    latent_channels: 64

    down_block_types: [
      'DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D', 
    ]
    up_block_types: [
      'UpDecoderBlock2D', 'UpDecoderBlock2D','UpDecoderBlock2D',
    ]
    
    block_out_channels: [
       128, 256, 512
    ]

    layers_per_block: 2
    act_fn: 'silu'
    norm_num_groups: 8
    sample_points_num: 16

    kl_weight: 0.000005

    # B-spline specific parameters
    bspline_cp_weight: 1.0      # Weight for B-spline reconstruction loss
    bspline_surface_weight: 1.0        # Weight for B-spline reconstruction loss
    mlp_hidden_dim: 256        # Hidden dimension for control point MLP

    checkpoint_folder: checkpoints/surface_vae_bs_from_scratch
    checkpoint_file_name: model-99.pt
    # load_checkpoint_from_file: checkpoints/surface_vae_bs/model-pretrained.pt