resume_training: false
from_start: false

epochs: 1000
batch_size: 256
lr: 0.0001
num_workers: 6
num_gpus: 5

grad_accum_every: 1
ema_update_every: 10
max_grad_norm: 1.0

val_every_epoch: 5
save_every_epoch: 20
log_every_step: 50

use_wandb_tracking: true
wandb_project_name: CLR-adjacency
wandb_run_name: surface_adjacency_30filtered_transform_rand_order_fix_rand

data:
    replication: 1
    transform: scale_and_jitter_and_rotate
    train_data_path: /home/qindafei/CAD/data/json/adjacency/train_files.pkl
    val_data_path: /home/qindafei/CAD/data/json/adjacency/val_files.pkl
    train_data_dir: /home/qindafei/CAD/data/json/adjacency/train
    val_data_dir: /home/qindafei/CAD/data/json/adjacency/val

model:
    depth: 16
    dim: 512
    heads: 8
    surface_res: 32
    num_types: 6
    num_nearby: 20
    surface_dim: 256
    surface_enc_block_out_channels: [16, 32, 64, 128]
    checkpoint_folder: checkpoints/adjacency-30filtered-transform-randorder
    checkpoint_file_name: model.pt 