resume_training: true
from_start: false

epochs: 400
batch_size: 768
lr: 0.0003
num_workers: 48
num_gpus: 6

grad_accum_every: 2
ema_update_every: 20
max_grad_norm: 5.

val_every_epoch: 1
save_every_epoch: 10
log_every_step: 10

use_wandb_tracking: true
wandb_project_name: CLR-wire
wandb_run_name: try_run_2


DATA:
    train_set_file_path: /home/qindafei/CAD/curve_wireframe_split/edge_points_concat_train.npy
    val_set_file_path: /home/qindafei/CAD/curve_wireframe_split/edge_points_concat_val.npy
    replication: 1
    recon_dir_path: /home/qindafei/CAD/curve_wireframe_split/edge_points_concat_train.npy

MODEL:
    in_channels: 3
    out_channels: 3
    latent_channels: 3

    down_block_types: [
      'DownBlock1D', 'DownBlock1D', 'DownBlock1D', 'DownBlock1D'
    ]
    up_block_types: [
      'UpBlock1D', 'UpBlock1D', 'UpBlock1D', 'UpBlock1D'
    ]
    
    block_out_channels: [
      64, 128, 256, 512
    ]

    layers_per_block: 2
    act_fn: 'silu'
    norm_num_groups: 32
    sample_points_num: 64

    kl_weight: 0.000005

    checkpoint_folder: checkpoints/checkpoints_curve_vae
    checkpoint_file_name: model-04.pt
